force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Пациент</label>
    <nameField>
        <label>A/K</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Пациенты</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>Имя</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Телефон</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Patronymic__c.field-meta.xml
<CustomField>
    <fullName>Patronymic__c</fullName>
    <label>Отчество</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Second_Name__c.field-meta.xml
<CustomField>
    <fullName>Second_Name__c</fullName>
    <label>Фамилия</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sick_leave__c/Sick_leave__c.object-meta.xml
<CustomObject>
    <label>Больничный</label>
    <nameField>
        <label>Номер больничного</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Больничные</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sick_leave__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Пациент</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Больничные</relationshipLabel>
    <relationshipName>Patient</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BuilderPatient.cls
public with sharing class BuilderPatient {
    private String secondName;
    private String firstName;
    private String patronymic;

    public BuilderPatient(String secondName, String firstName, String patronymic){
        this.secondName = secondName;
        this.firstName = firstName;
        this.patronymic = patronymic;
    }

    public BuilderPatient(Sick_leave__c sickLeave){
        SObject patient = BuilderPatient.getPatientSObject(sickLeave);
        if (patient != null) {
            this.secondName = (String) patient.get('Second_Name__c');
            this.firstName = (String) patient.get('First_Name__c');
            this.patronymic = (String) patient.get('Patronymic__c');
        }
    }

    public String buildNameInitials(){
        String result = '';
        String resultTemplate = '{0} {1}.{2}.';

        if (String.isNotEmpty(this.secondName) && String.isNotEmpty(this.firstName) && String.isNotEmpty(this.patronymic)) {
            List<String> templateList = new List<String>{
                this.secondName, this.firstName.left(1), this.patronymic.left(1)
            };
            result = String.format(resultTemplate, templateList);
        }

        return result;
    }

    public String buildNameFull(){
        String result = '';
        String resultTemplate = '{0} {1} {2}';

        if (String.isNotEmpty(this.secondName) && String.isNotEmpty(this.firstName) && String.isNotEmpty(this.patronymic)) {
            List<String> templateList = new List<String>{
                this.secondName, this.firstName, this.patronymic
            };
            result = String.format(resultTemplate, templateList);
        }

        return result;
    }

    public static String getPhoneFieldValue(Sick_leave__c sickLeave) {
        String phone;
        SObject patient = BuilderPatient.getPatientSObject(sickLeave);

        if (patient != null) {
            phone = (String) patient.get('Mobile__c');
        }

        return phone;
    }

    private static SObject getPatientSObject(Sick_leave__c sickLeave){
        SObject patient;

        if (sickLeave != null) {
            patient = sickLeave.getSObject('Patient__r');
        }

        return patient;
    }
}